use hypertree::RBTREE_OVERHEAD_BYTES;

pub const MARKET_FIXED_SIZE: usize = 512;

pub const MARKET_BLOCK_SIZE: usize = 160;

const MARKET_BLOCK_PAYLOAD_SIZE: usize = MARKET_BLOCK_SIZE - RBTREE_OVERHEAD_BYTES;

pub const RESTING_ORDER_SIZE: usize = MARKET_BLOCK_PAYLOAD_SIZE;
pub const CLAIMED_SEAT_SIZE: usize = MARKET_BLOCK_PAYLOAD_SIZE;

pub const MATCHED_LOAN_SIZE: usize = MARKET_BLOCK_PAYLOAD_SIZE;

const FREE_LIST_OVERHEAD: usize = 4;
pub const MARKET_FREE_LIST_BLOCK_SIZE: usize = MARKET_BLOCK_SIZE - FREE_LIST_OVERHEAD;

pub const NO_EXPIRATION_LAST_VALID_UNIX_TS: i64 = 0;

pub const MARKET_FIXED_DISCRIMINANT: u64 = 0x79_64_65_6C_74_61_4D_4B;

pub const ACCOUNT_LAYOUT_VERSION: u8 = 1;

pub const MIN_PRINCIPAL_ATOMS: u64 = 1;

pub const USER_ACCOUNT_FIXED_SIZE: usize = 128;

pub const USER_ACCOUNT_FIXED_DISCRIMINANT: u64 = 0x79_64_65_6C_74_61_55_53;

pub const USER_ACCOUNT_BLOCK_SIZE: usize = MARKET_BLOCK_SIZE;
pub const USER_ACCOUNT_BLOCK_PAYLOAD_SIZE: usize = USER_ACCOUNT_BLOCK_SIZE - RBTREE_OVERHEAD_BYTES;
pub const USER_ACCOUNT_FREE_LIST_BLOCK_SIZE: usize = USER_ACCOUNT_BLOCK_SIZE - FREE_LIST_OVERHEAD;

pub const VAULT_POSITION_SIZE: usize = USER_ACCOUNT_BLOCK_PAYLOAD_SIZE;
pub const MARKET_POSITION_SIZE: usize = USER_ACCOUNT_BLOCK_PAYLOAD_SIZE;
pub const USER_LOAN_REF_SIZE: usize = USER_ACCOUNT_BLOCK_PAYLOAD_SIZE;

pub const GLOBAL_VAULT_FIXED_SIZE: usize = 320;

pub const GLOBAL_VAULT_FIXED_DISCRIMINANT: u64 = 0x79_64_65_6C_74_61_56_61;

pub const RISK_PROFILE_BLOCK_SIZE: usize = 512;
pub const RISK_PROFILE_BLOCK_PAYLOAD_SIZE: usize = RISK_PROFILE_BLOCK_SIZE - RBTREE_OVERHEAD_BYTES;
pub const RISK_PROFILE_FREE_LIST_BLOCK_SIZE: usize = RISK_PROFILE_BLOCK_SIZE - FREE_LIST_OVERHEAD;
pub const RISK_PROFILE_SIZE: usize = RISK_PROFILE_BLOCK_PAYLOAD_SIZE;

pub const VAULT_NODE_BLOCK_SIZE: usize = MARKET_BLOCK_SIZE;
pub const VAULT_NODE_BLOCK_PAYLOAD_SIZE: usize = VAULT_NODE_BLOCK_SIZE - RBTREE_OVERHEAD_BYTES;
pub const VAULT_NODE_FREE_LIST_BLOCK_SIZE: usize = VAULT_NODE_BLOCK_SIZE - FREE_LIST_OVERHEAD;
pub const VAULT_CLAIMED_SEAT_SIZE: usize = VAULT_NODE_BLOCK_PAYLOAD_SIZE;
pub const VAULT_ORDER_REF_SIZE: usize = VAULT_NODE_BLOCK_PAYLOAD_SIZE;
