import { IdlErrorCode } from './format';

/** Program-level errors (0–58) and adapter-side errors (100–106). */
export const errors: IdlErrorCode[] = [
  // ─── YdeltaError (program-level) ───
  { code: 0, name: 'InvalidMarketParameters', msg: 'Invalid market parameters' },
  { code: 1, name: 'InvalidDepositAccounts', msg: 'Invalid deposit accounts' },
  { code: 2, name: 'InvalidWithdrawAccounts', msg: 'Invalid withdraw accounts' },
  { code: 3, name: 'InvalidCancel', msg: 'Invalid cancel' },
  { code: 4, name: 'InvalidFreeList', msg: 'Internal free list corruption' },
  { code: 5, name: 'AlreadyClaimedSeat', msg: 'Cannot claim a second seat for the same trader' },
  { code: 6, name: 'PostOnlyWouldCross', msg: 'PostOnly order would cross the book' },
  { code: 7, name: 'OrderAlreadyExpired', msg: 'Order is already expired' },
  { code: 8, name: 'WrongIndexHintParams', msg: 'Index hint did not match the actual order' },
  { code: 9, name: 'Overflow', msg: 'Numeric overflow' },
  { code: 10, name: 'IncorrectAccount', msg: 'Account key did not match expected' },
  { code: 11, name: 'InvalidMint', msg: 'Mint not allowed for this market' },
  { code: 12, name: 'NoSeatClaimed', msg: 'Trader has no claimed seat in this market' },
  { code: 13, name: 'SeatHasOpenObligations', msg: 'Seat still has open obligations' },
  { code: 14, name: 'InsufficientWithdrawableBalance', msg: 'Withdraw exceeds withdrawable balance' },
  { code: 15, name: 'RateBelowFloor', msg: 'Cross fails the protocol-fee floor gate' },
  { code: 16, name: 'TermNotCompatible', msg: "Bid term exceeds ask's max lock-up" },
  { code: 17, name: 'CollateralInsufficient', msg: 'Collateral too low for the requested principal' },
  { code: 18, name: 'Token2022UnsupportedExtension', msg: 'Token-2022 mint has an unsupported extension' },
  { code: 19, name: 'OrderNotFound', msg: 'Order does not exist' },
  { code: 20, name: 'OrderNotOwnedBySigner', msg: 'Order is not owned by the signer' },
  { code: 21, name: 'InvalidArgument', msg: 'Generic invalid argument' },
  { code: 22, name: 'MatchedLoanNotFound', msg: 'MatchedLoan not found in market' },
  { code: 23, name: 'SelfMatchForbidden', msg: 'Self-match forbidden: taker and maker share a seat' },
  { code: 24, name: 'CollateralBelowMatchLTV', msg: 'Matched collateral below required LTV at current oracle prices' },
  { code: 25, name: 'SecondaryNotCurrentLender', msg: "SecondaryLoanSale: signer's seat is not the loan's current lender" },
  { code: 26, name: 'SecondaryDuplicate', msg: 'SecondaryLoanSale: a resting secondary bid already exists for this loan' },
  { code: 27, name: 'SecondaryOrderTypeInvalid', msg: 'SecondaryLoanSale: only Limit order_type is permitted for secondary bids' },
  { code: 28, name: 'SecondaryLoanWrongType', msg: 'SecondaryLoanSale: target loan must be Fixed' },
  { code: 29, name: 'SecondaryLoanSettled', msg: 'SecondaryLoanSale: target loan has no outstanding debt' },
  { code: 30, name: 'SecondarySplitLtvFailed', msg: 'SecondaryLoanSale split: post-split LTV check failed' },
  { code: 31, name: 'SecondaryFieldImmutable', msg: 'SecondaryLoanSale: rate / term / principal / collateral are loan-snapshots' },
  { code: 32, name: 'SecondaryLoanMatured', msg: 'SecondaryLoanSale: target loan has matured' },
  { code: 33, name: 'VaultWrongMint', msg: 'vault: passed mint does not match GlobalVaultFixed.mint' },
  { code: 34, name: 'VaultProfileNotFound', msg: 'vault: profile_id not found in vault.risk_profiles tree' },
  { code: 35, name: 'VaultProfileAllowedMarketsExceeded', msg: 'create_risk_profile: allowed_market_max exceeds cap (8)' },
  { code: 36, name: 'VaultOrderTermExceedsProfileMax', msg: 'vault order: term_seconds exceeds RiskProfile.max_term_seconds' },
  { code: 37, name: 'VaultCuratorRequired', msg: 'vault: signer is not RiskProfile.curator' },
  { code: 38, name: 'VaultAdminRequired', msg: 'vault: signer is not GlobalVaultFixed.global_vault_admin' },
  { code: 39, name: 'VaultProfileSeatExists', msg: 'claim_seat_for_risk_profile: seat already exists for (vault, profile_id) in this market' },
  { code: 40, name: 'VaultProfileOrderExists', msg: 'place_order_for_risk_profile: RiskProfileOrderRef already exists for (market, profile_id)' },
  { code: 41, name: 'VaultInsufficientIdleAtoms', msg: 'global_vault_withdraw: idle_principal_atoms < requested atoms' },
  { code: 42, name: 'VaultProfileNotEmpty', msg: 'vault: profile has nonzero seats / orders / loans / shares' },
  { code: 43, name: 'VaultMarketExposureCapExceeded', msg: 'vault order: filled atoms would exceed max_exposure_atoms' },
  { code: 44, name: 'VaultProfileIdExists', msg: 'create_risk_profile: profile_id already exists in vault' },
  { code: 45, name: 'VaultProfileLtvOutOfRange', msg: 'create_risk_profile: max_ltv_bps must be between 1 and 9_999' },
  { code: 46, name: 'VaultProfileTermInvalid', msg: 'create_risk_profile: max_term_seconds must be > 0' },
  { code: 47, name: 'LoanNotMatured', msg: 'settle_matured_loan: now <= matures_at_unix + grace_period_seconds' },
  { code: 48, name: 'LoanStillSolvent', msg: 'liquidate_loan: current LTV is below maintenance_ltv' },
  { code: 49, name: 'LiquidatorPaymentInsufficient', msg: "liquidator's debt_token has insufficient atoms" },
  { code: 50, name: 'LiquidationCollateralUnderflow', msg: 'collateral_atoms < required debt-equivalent + bonus' },
  { code: 51, name: 'MarketAdminRequired', msg: 'market admin signer required' },
  { code: 52, name: 'InvalidFeeConfig', msg: 'invalid fee config: bps field exceeds 10_000' },
  { code: 53, name: 'PendingAdminMismatch', msg: 'admin transfer accept: signer != pending_admin' },
  { code: 54, name: 'MarketPaused', msg: 'market is paused' },
  { code: 55, name: 'GlobalPaused', msg: 'global pause active' },
  { code: 56, name: 'ProtocolAdminRequired', msg: 'protocol admin signer required' },
  { code: 57, name: 'BorrowerLtvExceeded', msg: "borrower_ltv: actual loan LTV exceeds borrower's declared cap" },
  { code: 58, name: 'BorrowerLtvOverInit', msg: "borrower_ltv: declared value exceeds marginfi's init LTV ceiling" },
  // ─── AdapterError (CPI / oracle adapter, 100–106) ───
  { code: 100, name: 'UnexpectedAtomDelta', msg: 'Post-CPI atom delta deviated from expected by more than 1 atom' },
  { code: 101, name: 'InvalidIntegrationAccount', msg: 'Integration account header had the wrong discriminator' },
  { code: 102, name: 'OracleStale', msg: 'Oracle price was older than the configured staleness threshold' },
  { code: 103, name: 'OracleSetupUnsupported', msg: "Bank's oracle_setup is unsupported" },
  { code: 104, name: 'OracleMaxConfidenceExceeded', msg: "Confidence interval exceeded bank's oracle_max_confidence" },
  { code: 105, name: 'OracleAccountMismatch', msg: "Caller supplied oracle account doesn't match bank's pubkey" },
  { code: 106, name: 'OracleNonPositive', msg: 'Oracle reported a non-positive price' },
];
