/**
 * Instruction discriminant tags. Must stay byte-identical to the on-chain
 * `YdeltaInstruction` enum in `programs/ydelta/src/program/instruction.rs`.
 *
 * Tags are a contiguous `0..=44` range. The processor `TryFrom<u8>` rejects
 * anything outside that range, so unknown tags fail at the loader.
 */
export enum InstructionTag {
  CreateMarket = 0,
  ClaimSeat = 1,
  Deposit = 2,
  Withdraw = 3,
  PlaceOrder = 4,
  ProcessMatchedLoan = 5,
  Repay = 6,
  SyncMarketPosition = 7,
  CreateVault = 8,
  CreatePoolSubVault = 9,
  GlobalVaultDeposit = 10,
  GlobalVaultWithdraw = 11,
  PlaceOrderForSubVault = 12,
  CancelOrderForSubVault = 13,
  UpdateOrderForSubVault = 14,
  ClaimCuratorFee = 15,
  SettleMaturedLoan = 16,
  LiquidateLoan = 17,
  SetFeeConfig = 18,
  ProtocolFeeClaim = 19,
  ClaimRepaymentForSubVault = 20,
  TransferMarketAdmin = 21,
  AcceptMarketAdmin = 22,
  TransferGlobalVaultAdmin = 23,
  AcceptGlobalVaultAdmin = 24,
  TransferCurator = 25,
  AcceptCurator = 26,
  SetMarketPause = 27,
  CreateGlobalConfig = 28,
  TransferProtocolAdmin = 29,
  AcceptProtocolAdmin = 30,
  SetGlobalPause = 31,
  UpdateSubVault = 32,
  ConvertP2PoolToFixed = 33,
  CheckLtvLiquidatable = 34,
  CheckMaturityLiquidatable = 35,
  SetVaultPause = 36,
  RemoveSubVault = 37,
  SunsetSubVault = 38,
  ResumeSubVault = 39,
  AdminCancelSubVaultOrder = 40,
  CreatePrivateSubVault = 41,
  CancelOrder = 42,
  MatchCrank = 43,
  UpdateOrder = 44,
}
